### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mansimransingh** [facebook/lexical-ios#39]
Hi - I'm not sure if im doing something wrong, or this is a known issue (altho i couldn't find any references to this in PRs or issues).

There are memory leaks caused by internal circular references. I thought was a SwiftUI weirdness, but even a simplest UIKit app leads to leaked Editor and associated objects.

Here's a minimally reproducible example:
https://github.com/mansimransingh/lexical-ios/tree/memory-leak-test

It is the example app, which pushes and pops the ViewController, leaking an Editor each time.

I'm going to try dig into this to resolve it. 

But was wondering if am expected to do manual cleanup or something, or if this is a known issue.

Thoughts?

**Comment by mansimransingh** [comment]
Okay I managed to narrow things down. 

I fixed 2/3 memory leaks in this branch:
https://github.com/mansimransingh/lexical-ios/tree/memory-leak-fixes

I can open a PR for these.

The other memory leaks are in History Plugin, specifically in HistoryState/HistoryStateEntry. For my use case, I'm disabling history for now. I might come around to fixing them later.

**Comment by amyworrall** [comment]
Thanks @mansimransingh . You're definitely not expected to do manual cleanup; these were just bugs!

I'll have a look at HistoryPlugin.

**Comment by mansimransingh** [comment]
Closing. Cause we resolved it =)
